version: "3.7"

networks:
  extnetwork:
    ipam:
      config:
        - subnet: 192.168.0.0/16

x-variables:
  etcd_flag_initial_cluster_token: &etcd_flag_initial_cluster_token '--initial-cluster-token=mys3cr3ttok3n'
  etcd_common_settings: &etcd_common_settings
    image: quay.io/coreos/etcd:v2.3.8
    # entrypoint: /usr/local/bin/etcd
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 2379
      - 2380
      - 4001
  pika_server_common_settings: &pika_server_common_settings
    image: pika/pika_build:v0.1
    environment:
      - TZ=Asia/Shanghai
    command: /pika/output/pika -c /pika.conf
    ports:
      - 9221
      - 10221 # 9221 + 1000
      - 11221 # 9221 + 2000
      - 19222 # 9221 + 10001
  codis_common_settings: &codis_common_settings
    image: centos:7
    volumes:
      - ../codis:/codis:ro
    environment:
      - TZ=Asia/Shanghai

services:
  codis_fe:
    <<: *codis_common_settings
    hostname: 192.168.0.4
    command: /codis/bin/codis-fe --assets-dir=/codis/bin/assets --etcd=192.168.2.1:2379 --log-level=DEBUG --listen=0.0.0.0:9090
    depends_on:
      - codis_dashboard
      - pika_server1
      - pika_server2
      - pika_server3
      - pika_server4
    ports:
      - 9090:9090
    networks:
      extnetwork:
        ipv4_address: 192.168.0.4
  codis_proxy:
    <<: *codis_common_settings
    hostname: 192.168.0.2
    command: /codis/bin/codis-proxy --config=/codis/config/proxy.toml --dashboard=192.168.0.3:18080 --log-level=DEBUG --pidfile=/codis/codis-proxy.pid
    depends_on:
      - codis_dashboard
    ports:
      - 19000:19000
    networks:
      extnetwork:
        ipv4_address: 192.168.0.2
  codis_dashboard:
    <<: *codis_common_settings
    hostname: 192.168.0.3
    command: /codis/bin/codis-dashboard --config=/codis/config/dashboard.toml --etcd=192.168.2.1:2379 --log-level=DEBUG --pidfile=/codis/codis-dashboard.pid
    depends_on:
      - etcd_cluster
    ports:
      - 18080
    networks:
      extnetwork:
        ipv4_address: 192.168.0.3
  pika_server1:
    <<: *pika_server_common_settings
    hostname: 192.168.1.1
    container_name: pika_server1
    volumes:
      - ../output:/pika/output:ro
    networks:
      extnetwork:
        ipv4_address: 192.168.1.1
  pika_server2:
    <<: *pika_server_common_settings
    hostname: 192.168.1.2
    container_name: pika_server2
    volumes:
      - ../output:/pika/output:ro
    networks:
      extnetwork:
        ipv4_address: 192.168.1.2
  pika_server3:
    <<: *pika_server_common_settings
    hostname: 192.168.1.3
    container_name:  pika_server3
    volumes:
      - ../output:/pika/output:ro
    networks:
      extnetwork:
        ipv4_address: 192.168.1.3
  pika_server4:
    <<: *pika_server_common_settings
    hostname: 192.168.1.4
    container_name:  pika_server4
    volumes:
      - ../output:/pika/output:ro
    networks:
      extnetwork:
        ipv4_address: 192.168.1.4
  etcd_cluster:
    <<: *etcd_common_settings
    depends_on: 
      - etcd_1
      - etcd_2
      - etcd_3
  etcd_1:
    <<: *etcd_common_settings
    hostname: 192.168.2.1
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://192.168.2.1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001'
      - '--advertise-client-urls=http://192.168.2.1:2379,http://192.168.2.1:4001'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://192.168.2.1:2380,etcd-2=http://192.168.2.2:2380,etcd-3=http://192.168.2.3:2380'
      - '--initial-cluster-state=new'
      - *etcd_flag_initial_cluster_token
    volumes:
      - etcd1:/etcd_data
    networks:
      extnetwork:
        ipv4_address: 192.168.2.1

  etcd_2:
    <<: *etcd_common_settings
    hostname: 192.168.2.2
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://192.168.2.2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001'
      - '--advertise-client-urls=http://192.168.2.2:2379,http://192.168.2.1:4001'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://192.168.2.1:2380,etcd-2=http://192.168.2.2:2380,etcd-3=http://192.168.2.3:2380'
      - '--initial-cluster-state=new'
      - *etcd_flag_initial_cluster_token
    volumes:
      - etcd2:/etcd_data
    networks:
      extnetwork:
        ipv4_address: 192.168.2.2

  etcd_3:
    <<: *etcd_common_settings
    hostname: 192.168.2.3
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://192.168.2.3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001'
      - '--advertise-client-urls=http://192.168.2.3:2379,http://192.168.2.1:4001'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://192.168.2.1:2380,etcd-2=http://192.168.2.2:2380,etcd-3=http://192.168.2.3:2380'
      - '--initial-cluster-state=new'
      - *etcd_flag_initial_cluster_token
    volumes:
      - etcd3:/etcd_data
    networks:
      extnetwork:
        ipv4_address: 192.168.2.3

volumes:
  etcd1:
  etcd2:
  etcd3:
